server:
  port: 5001

spring:
  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: Admin@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true


  mail:
    host: smtp.gmail.com
    port: 465
    username: eyobhabtie@gmail.com
    password: gbwc hnka dcug mren
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.gmail.com
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

logging:
  level:
    org.springframework.security: INFO
    com.task.user_service: DEBUG
    org.springframework.mail: DEBUG