export const mockAuditLogs = [
  {
    id: 'audit1',
    actorId: 'admin1',
    actorRole: 'ADMIN',
    action: 'FREEZE_ACCOUNT',
    entityType: 'ACCOUNT',
    entityId: 'acc3',
    oldValue: 'ACTIVE',
    newValue: 'FROZEN',
    description: 'Account frozen due to suspicious activity',
    ipAddress: '192.168.1.50',
    timestamp: '2024-02-26T08:30:00Z',
    severity: 'WARNING'
  },
  {
    id: 'audit2',
    actorId: 'admin1',
    actorRole: 'ADMIN',
    action: 'FLAG_TRANSACTION',
    entityType: 'TRANSACTION',
    entityId: 'tx3',
    oldValue: 'false',
    newValue: 'true',
    description: 'Transaction flagged for review',
    ipAddress: '192.168.1.50',
    timestamp: '2024-02-26T11:45:00Z',
    severity: 'INFO'
  },
  {
    id: 'audit3',
    actorId: 'admin1',
    actorRole: 'ADMIN',
    action: 'BLOCK_CARD',
    entityType: 'CARD',
    entityId: 'card5',
    oldValue: 'ACTIVE',
    newValue: 'BLOCKED',
    description: 'Card permanently blocked',
    ipAddress: '192.168.1.50',
    timestamp: '2024-02-25T16:45:00Z',
    severity: 'ERROR'
  },
  {
    id: 'audit4',
    actorId: 'admin1',
    actorRole: 'ADMIN',
    action: 'DISABLE_USER',
    entityType: 'USER',
    entityId: '3',
    oldValue: 'ACTIVE',
    newValue: 'DISABLED',
    description: 'User account disabled',
    ipAddress: '192.168.1.50',
    timestamp: '2024-02-20T14:20:00Z',
    severity: 'WARNING'
  },
  {
    id: 'audit5',
    actorId: 'admin1',
    actorRole: 'ADMIN',
    action: 'REVERSE_TRANSACTION',
    entityType: 'TRANSACTION',
    entityId: 'tx7',
    oldValue: 'SUCCESS',
    newValue: 'REVERSED',
    description: 'Transaction reversed due to fraud suspicion',
    ipAddress: '192.168.1.50',
    timestamp: '2024-02-26T15:45:00Z',
    severity: 'CRITICAL'
  },
  {
    id: 'audit6',
    actorId: 'admin1',
    actorRole: 'ADMIN',
    action: 'UPDATE_SPENDING_LIMIT',
    entityType: 'CARD',
    entityId: 'card2',
    oldValue: '50000',
    newValue: '100000',
    description: 'Card spending limit increased',
    ipAddress: '192.168.1.50',
    timestamp: '2024-02-24T10:15:00Z',
    severity: 'INFO'
  },
  {
    id: 'audit7',
    actorId: 'admin1',
    actorRole: 'ADMIN',
    action: 'SET_PREMIUM_STATUS',
    entityType: 'USER',
    entityId: '2',
    oldValue: 'false',
    newValue: 'true',
    description: 'User upgraded to premium status',
    ipAddress: '192.168.1.50',
    timestamp: '2024-02-15T09:30:00Z',
    severity: 'INFO'
  },
  {
    id: 'audit8',
    actorId: 'system',
    actorRole: 'SYSTEM',
    action: 'LOGIN_ATTEMPT',
    entityType: 'USER',
    entityId: '1',
    oldValue: null,
    newValue: 'SUCCESS',
    description: 'User login successful',
    ipAddress: '192.168.1.100',
    timestamp: '2024-02-26T09:00:00Z',
    severity: 'INFO'
  },
  {
    id: 'audit9',
    actorId: 'admin1',
    actorRole: 'ADMIN',
    action: 'FREEZE_CARD',
    entityType: 'CARD',
    entityId: 'card3',
    oldValue: 'ACTIVE',
    newValue: 'FROZEN',
    description: 'Card frozen due to suspicious activity',
    ipAddress: '192.168.1.50',
    timestamp: '2024-02-25T14:20:00Z',
    severity: 'WARNING'
  },
  {
    id: 'audit10',
    actorId: 'admin1',
    actorRole: 'ADMIN',
    action: 'CLOSE_ACCOUNT',
    entityType: 'ACCOUNT',
    entityId: 'acc5',
    oldValue: 'ACTIVE',
    newValue: 'CLOSED',
    description: 'Account closed by admin',
    ipAddress: '192.168.1.50',
    timestamp: '2024-02-20T16:30:00Z',
    severity: 'WARNING'
  }
];
